Topic/admin product categories 20200902
Baisel/shopping pull request #1
Opened 2020-09-02 08:15 UTC by Baisel

管理者ページの商品カテゴリ管理部分が完成したので、レビューをお手すきの際にレビューお願いします

2020-09-03 04:51 UTC, Baisel commented
指摘頂いた部分を修正できたので、再度レビューをよろしくお願いします。

2020-09-07 06:45 UTC, Baisel commented
指摘頂いた部分を修正できたので、再度レビューをよろしくお願いします。

2020-09-08 09:04 UTC, nakama-t commented on application/app/Http/Controllers/Admin/ProductCategoriesController.php
> +        return redirect('/admin/product_categories/' . $product_category->id);
これroute()で表現できるよね

2020-09-08 09:06 UTC, nakama-t commented on application/app/Http/Controllers/Admin/ProductCategoriesController.php
> +        return view('admin.product_categories.show', compact('product_category'));
storeはリダイレクトしてるのになんでこっちはしないの？

2020-09-08 09:10 UTC, nakama-t commented on application/database/seeds/ProductCategoriesSeeder.php
> +                'order_no' =>'1'
stringとかint混じってる
統一しようよ

2020-09-08 09:11 UTC, nakama-t commented on application/database/seeds/ProductCategoriesSeeder.php
> +                'order_no' =>'1'
あとスペースないのも気になる

2020-09-08 09:18 UTC, nakama-t requested changes
要修正

2020-09-09 02:35 UTC, Baisel commented
不要な空白の修正と指摘いただいた部分の修正を行いましたので、確認お願いします

2020-09-28 09:31 UTC, nakama-t approved these changes

2020-09-28 09:32 UTC, merged